#to run: make
pq: PQueue.o PQueueTst.o queue2.o list2.o
	g++ -o pq PQueue.o PQueueTst.o queue2.o list2.o

PQueue.o: PQueue.cpp
	g++ -c PQueue.cpp

PQueueTst.o: PQueueTst.cpp
	g++ -c PQueueTst.cpp

queue2.o: queue2.cpp
	g++ -c queue2.cpp

list2.o: list2.cpp
	g++ -c list2.cpp
